# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/apps/adonisjs' # Location of package manifests
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/apps/auth0-user-store' # Location of package manifests
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/apps/directory-sync' # Location of package manifests
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/apps/directory-sync-embedded' # Location of package manifests
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/apps/express' # Location of package manifests
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/apps/express-api' # Location of package manifests
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/apps/firebase-user-store' # Location of package manifests
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/apps/hasura-express' # Location of package manifests
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/apps/hasura-nextjs' # Location of package manifests
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/apps/next-auth' # Location of package manifests
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/apps/react-example' # Location of package manifests
    schedule:
      interval: 'monthly'
